# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Yönetici.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Yonetici(object):
    def setupUi(self, Yonetici):
        Yonetici.setObjectName("Yonetici")
        Yonetici.resize(844, 593)
        self.centralwidget = QtWidgets.QWidget(Yonetici)
        self.centralwidget.setObjectName("centralwidget")
        self.grp_kitap = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_kitap.setGeometry(QtCore.QRect(20, 10, 251, 551))
        self.grp_kitap.setObjectName("grp_kitap")
        self.widget = QtWidgets.QWidget(self.grp_kitap)
        self.widget.setGeometry(QtCore.QRect(1, 21, 251, 531))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rdr_k1 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k1.setObjectName("rdr_k1")
        self.gridLayout_2.addWidget(self.rdr_k1, 0, 0, 1, 1)
        self.rdr_k2 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k2.setObjectName("rdr_k2")
        self.gridLayout_2.addWidget(self.rdr_k2, 1, 0, 1, 1)
        self.rdr_k3 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k3.setObjectName("rdr_k3")
        self.gridLayout_2.addWidget(self.rdr_k3, 2, 0, 1, 1)
        self.rdr_k4 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k4.setObjectName("rdr_k4")
        self.gridLayout_2.addWidget(self.rdr_k4, 3, 0, 1, 1)
        self.rdr_k5 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k5.setObjectName("rdr_k5")
        self.gridLayout_2.addWidget(self.rdr_k5, 4, 0, 1, 1)
        self.rdr_k6 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k6.setObjectName("rdr_k6")
        self.gridLayout_2.addWidget(self.rdr_k6, 5, 0, 1, 1)
        self.rdr_k7 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k7.setObjectName("rdr_k7")
        self.gridLayout_2.addWidget(self.rdr_k7, 6, 0, 1, 1)
        self.rdr_k8 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k8.setObjectName("rdr_k8")
        self.gridLayout_2.addWidget(self.rdr_k8, 7, 0, 1, 1)
        self.rdr_k9 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k9.setObjectName("rdr_k9")
        self.gridLayout_2.addWidget(self.rdr_k9, 8, 0, 1, 1)
        self.rdr_k10 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k10.setObjectName("rdr_k10")
        self.gridLayout_2.addWidget(self.rdr_k10, 9, 0, 1, 1)
        self.rdr_k11 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k11.setObjectName("rdr_k11")
        self.gridLayout_2.addWidget(self.rdr_k11, 10, 0, 1, 1)
        self.rdr_k12 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k12.setObjectName("rdr_k12")
        self.gridLayout_2.addWidget(self.rdr_k12, 11, 0, 1, 1)
        self.rdr_k13 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k13.setObjectName("rdr_k13")
        self.gridLayout_2.addWidget(self.rdr_k13, 12, 0, 1, 1)
        self.rdr_k14 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k14.setObjectName("rdr_k14")
        self.gridLayout_2.addWidget(self.rdr_k14, 13, 0, 1, 1)
        self.rdr_k15 = QtWidgets.QRadioButton(self.widget)
        self.rdr_k15.setObjectName("rdr_k15")
        self.gridLayout_2.addWidget(self.rdr_k15, 14, 0, 1, 1)
        self.btn_ycks = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ycks.setGeometry(QtCore.QRect(280, 490, 171, 28))
        self.btn_ycks.setObjectName("btn_ycks")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(460, 10, 371, 541))
        self.groupBox.setObjectName("groupBox")
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(0, 20, 371, 521))
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.grp_ahmet = QtWidgets.QGroupBox(self.widget1)
        self.grp_ahmet.setObjectName("grp_ahmet")
        self.lbl_a1 = QtWidgets.QLabel(self.grp_ahmet)
        self.lbl_a1.setGeometry(QtCore.QRect(10, 20, 141, 51))
        self.lbl_a1.setText("")
        self.lbl_a1.setObjectName("lbl_a1")
        self.lbl_a2 = QtWidgets.QLabel(self.grp_ahmet)
        self.lbl_a2.setGeometry(QtCore.QRect(160, 10, 201, 61))
        self.lbl_a2.setText("")
        self.lbl_a2.setObjectName("lbl_a2")
        self.gridLayout_4.addWidget(self.grp_ahmet, 0, 0, 1, 1)
        self.grp_bekirhan = QtWidgets.QGroupBox(self.widget1)
        self.grp_bekirhan.setObjectName("grp_bekirhan")
        self.lbl_b1 = QtWidgets.QLabel(self.grp_bekirhan)
        self.lbl_b1.setGeometry(QtCore.QRect(10, 20, 141, 51))
        self.lbl_b1.setText("")
        self.lbl_b1.setObjectName("lbl_b1")
        self.lbl_b2 = QtWidgets.QLabel(self.grp_bekirhan)
        self.lbl_b2.setGeometry(QtCore.QRect(160, 20, 201, 51))
        self.lbl_b2.setText("")
        self.lbl_b2.setObjectName("lbl_b2")
        self.gridLayout_4.addWidget(self.grp_bekirhan, 1, 0, 1, 1)
        self.grp_furkan = QtWidgets.QGroupBox(self.widget1)
        self.grp_furkan.setObjectName("grp_furkan")
        self.lbl_f1 = QtWidgets.QLabel(self.grp_furkan)
        self.lbl_f1.setGeometry(QtCore.QRect(10, 20, 131, 51))
        self.lbl_f1.setText("")
        self.lbl_f1.setObjectName("lbl_f1")
        self.lbl_f2 = QtWidgets.QLabel(self.grp_furkan)
        self.lbl_f2.setGeometry(QtCore.QRect(150, 10, 211, 61))
        self.lbl_f2.setText("")
        self.lbl_f2.setObjectName("lbl_f2")
        self.gridLayout_4.addWidget(self.grp_furkan, 2, 0, 1, 1)
        self.grp_mustafa = QtWidgets.QGroupBox(self.widget1)
        self.grp_mustafa.setObjectName("grp_mustafa")
        self.lbl_m1 = QtWidgets.QLabel(self.grp_mustafa)
        self.lbl_m1.setGeometry(QtCore.QRect(10, 20, 141, 51))
        self.lbl_m1.setText("")
        self.lbl_m1.setObjectName("lbl_m1")
        self.lbl_m2 = QtWidgets.QLabel(self.grp_mustafa)
        self.lbl_m2.setGeometry(QtCore.QRect(150, 10, 211, 61))
        self.lbl_m2.setText("")
        self.lbl_m2.setObjectName("lbl_m2")
        self.gridLayout_4.addWidget(self.grp_mustafa, 3, 0, 1, 1)
        self.grp_dogukan = QtWidgets.QGroupBox(self.widget1)
        self.grp_dogukan.setObjectName("grp_dogukan")
        self.lbl_d1 = QtWidgets.QLabel(self.grp_dogukan)
        self.lbl_d1.setGeometry(QtCore.QRect(10, 20, 141, 51))
        self.lbl_d1.setText("")
        self.lbl_d1.setObjectName("lbl_d1")
        self.lbl_d2 = QtWidgets.QLabel(self.grp_dogukan)
        self.lbl_d2.setGeometry(QtCore.QRect(160, 10, 201, 61))
        self.lbl_d2.setText("")
        self.lbl_d2.setObjectName("lbl_d2")
        self.gridLayout_4.addWidget(self.grp_dogukan, 4, 0, 1, 1)
        self.grp_mucahit = QtWidgets.QGroupBox(self.widget1)
        self.grp_mucahit.setObjectName("grp_mucahit")
        self.lbl_mu1 = QtWidgets.QLabel(self.grp_mucahit)
        self.lbl_mu1.setGeometry(QtCore.QRect(20, 20, 141, 51))
        self.lbl_mu1.setText("")
        self.lbl_mu1.setObjectName("lbl_mu1")
        self.lbl_mu2 = QtWidgets.QLabel(self.grp_mucahit)
        self.lbl_mu2.setGeometry(QtCore.QRect(160, 10, 201, 61))
        self.lbl_mu2.setText("")
        self.lbl_mu2.setObjectName("lbl_mu2")
        self.gridLayout_4.addWidget(self.grp_mucahit, 5, 0, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(281, 45, 171, 221))
        self.widget3.setObjectName("widget3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cmb_ogrenciler = QtWidgets.QComboBox(self.widget3)
        self.cmb_ogrenciler.setObjectName("cmb_ogrenciler")
        self.cmb_ogrenciler.addItem("")
        self.cmb_ogrenciler.addItem("")
        self.cmb_ogrenciler.addItem("")
        self.cmb_ogrenciler.addItem("")
        self.cmb_ogrenciler.addItem("")
        self.cmb_ogrenciler.addItem("")
        self.gridLayout.addWidget(self.cmb_ogrenciler, 0, 0, 1, 1)
        self.dte_tarih = QtWidgets.QDateEdit(self.widget3)
        self.dte_tarih.setCalendarPopup(True)
        self.dte_tarih.setDate(QtCore.QDate(2020, 12, 1))
        self.dte_tarih.setObjectName("dte_tarih")
        self.gridLayout.addWidget(self.dte_tarih, 1, 0, 1, 1)
        self.dte_tarih2 = QtWidgets.QDateEdit(self.widget3)
        self.dte_tarih2.setCalendarPopup(True)
        self.dte_tarih2.setDate(QtCore.QDate(2020, 12, 1))
        self.dte_tarih2.setObjectName("dte_tarih2")
        self.gridLayout.addWidget(self.dte_tarih2, 2, 0, 1, 1)
        self.btn_ktpekle = QtWidgets.QPushButton(self.widget3)
        self.btn_ktpekle.setObjectName("btn_ktpekle")
        self.gridLayout.addWidget(self.btn_ktpekle, 3, 0, 1, 1)
        self.btn_ktpal = QtWidgets.QPushButton(self.widget3)
        self.btn_ktpal.setObjectName("btn_ktpal")
        self.gridLayout.addWidget(self.btn_ktpal, 4, 0, 1, 1)
        Yonetici.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Yonetici)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 844, 21))
        self.menubar.setObjectName("menubar")
        Yonetici.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Yonetici)
        self.statusbar.setObjectName("statusbar")
        Yonetici.setStatusBar(self.statusbar)

        self.retranslateUi(Yonetici)
        QtCore.QMetaObject.connectSlotsByName(Yonetici)

    def retranslateUi(self, Yonetici):
        _translate = QtCore.QCoreApplication.translate
        Yonetici.setWindowTitle(_translate("Yonetici", "MainWindow"))
        self.grp_kitap.setTitle(_translate("Yonetici", "Kitaplar"))
        self.rdr_k1.setText(_translate("Yonetici", "Kitap1"))
        self.rdr_k2.setText(_translate("Yonetici", "Kitap2"))
        self.rdr_k3.setText(_translate("Yonetici", "Kitap3"))
        self.rdr_k4.setText(_translate("Yonetici", "Kitap4"))
        self.rdr_k5.setText(_translate("Yonetici", "Kitap5"))
        self.rdr_k6.setText(_translate("Yonetici", "Kitap6"))
        self.rdr_k7.setText(_translate("Yonetici", "Kitap7"))
        self.rdr_k8.setText(_translate("Yonetici", "Kitap8"))
        self.rdr_k9.setText(_translate("Yonetici", "Kitap9"))
        self.rdr_k10.setText(_translate("Yonetici", "Kitap10"))
        self.rdr_k11.setText(_translate("Yonetici", "Kitap11"))
        self.rdr_k12.setText(_translate("Yonetici", "Kitap12"))
        self.rdr_k13.setText(_translate("Yonetici", "Kitap13"))
        self.rdr_k14.setText(_translate("Yonetici", "Kitap14"))
        self.rdr_k15.setText(_translate("Yonetici", "Kitap15"))
        self.btn_ycks.setText(_translate("Yonetici", "Çıkış"))
        self.groupBox.setTitle(_translate("Yonetici", "Ögrenciler"))
        self.grp_ahmet.setTitle(_translate("Yonetici", "Ahmet 192106035"))
        self.grp_bekirhan.setTitle(_translate("Yonetici", "Bekirhan 192106010"))
        self.grp_furkan.setTitle(_translate("Yonetici", "Furkan 192106011"))
        self.grp_mustafa.setTitle(_translate("Yonetici", "Mustafa 192106012"))
        self.grp_dogukan.setTitle(_translate("Yonetici", "Doğukan 192106013"))
        self.grp_mucahit.setTitle(_translate("Yonetici", "Mücahit 192106014"))
        self.cmb_ogrenciler.setItemText(0, _translate("Yonetici", "Ahmet 192106035"))
        self.cmb_ogrenciler.setItemText(1, _translate("Yonetici", "Furkan 192106011"))
        self.cmb_ogrenciler.setItemText(2, _translate("Yonetici", "Mustafa 192106012"))
        self.cmb_ogrenciler.setItemText(3, _translate("Yonetici", "Doğukan 192106013"))
        self.cmb_ogrenciler.setItemText(4, _translate("Yonetici", "Mücahit 192106014"))
        self.cmb_ogrenciler.setItemText(5, _translate("Yonetici", "Bekirhan 192106010"))
        self.btn_ktpekle.setText(_translate("Yonetici", "Kitap ekle"))
        self.btn_ktpal.setText(_translate("Yonetici", "Kitap al"))
